version: "3.7"

services:

  websites:
    image: websites
    build:
      context: .
      dockerfile: Dockerfile
      args:
        mySqlHost: [TBD]
        mySqlDatabase: [TBD]
        mySqlDefaultUser: [TBD]
        realm: [TBD]
        reduceFoodWasteHost: [TBD]
        sshPassword: [TBD]        
    ports:
      - "80:80"
      - "443:443"
      - "8022:2222"
    restart: always
    volumes:
      - letsencrypt-config:/etc/letsencrypt
      - letsencrypt-data:/var/lib/letsencrypt

volumes: 
  letsencrypt-config:
  letsencrypt-data: