version: "3.7"

services:

  websites:
    image: websites
    build:
      context: .
      dockerfile: Dockerfile
      args:
        mySqlHost: [TBD]
        mySqlDefaultUser: [TBD]
        mySqlDatabase: [TBD]
        mySqlCharset: [TBD]
        realm: [TBD]
        reduceFoodWasteHost: [TBD]
        sshPassword: [TBD]
    ports:
      - "80:80"
      - "443:443"
      - "8022:2222"
    restart: always
