version: '3'
services:
  websites-osdevgrp:
    build: .
    image: websites-osdevgrp:latest
    container_name: websites-osdevgrp
    domainname: osdevgrp.local
    hostname: websites
    network_mode: "bridge"
    ports:
      - "8080:80"
      - "8443:443"
    extra_hosts:
      - "mysql.osdevgrp.local:127.0.0.1"
      - "mother.osdevgrp.local:127.0.0.1"